import { jsPDF } from "jspdf";

export const generatePDF = (content: string, filename: string = "document.pdf") => {
  const doc = new jsPDF();
  
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 15;
  const maxLineWidth = pageWidth - (margin * 2);
  
  let cursorY = 20;

  // Helper to add new page if needed
  const checkPageBreak = (height: number) => {
    if (cursorY + height > 280) {
      doc.addPage();
      cursorY = 20;
    }
  };

  // Title
  doc.setFontSize(10);
  doc.setTextColor(150);
  doc.text("Generated by India Mitra AI", pageWidth - margin, 10, { align: "right" });
  doc.setTextColor(0);

  const lines = content.split('\n');

  lines.forEach((line) => {
    const trimmedLine = line.trim();
    
    if (!trimmedLine) {
      cursorY += 5; // Paragraph spacing
      return;
    }

    if (trimmedLine.startsWith('# ')) {
      // H1
      doc.setFontSize(18);
      doc.setFont("helvetica", "bold");
      const text = trimmedLine.replace('# ', '');
      const splitText = doc.splitTextToSize(text, maxLineWidth);
      checkPageBreak(splitText.length * 10);
      doc.text(splitText, margin, cursorY);
      cursorY += (splitText.length * 10) + 5;
    } else if (trimmedLine.startsWith('## ')) {
      // H2
      doc.setFontSize(14);
      doc.setFont("helvetica", "bold");
      const text = trimmedLine.replace('## ', '');
      const splitText = doc.splitTextToSize(text, maxLineWidth);
      checkPageBreak(splitText.length * 8);
      doc.text(splitText, margin, cursorY);
      cursorY += (splitText.length * 8) + 4;
    } else if (trimmedLine.startsWith('### ')) {
      // H3
      doc.setFontSize(12);
      doc.setFont("helvetica", "bold");
      const text = trimmedLine.replace('### ', '');
      const splitText = doc.splitTextToSize(text, maxLineWidth);
      checkPageBreak(splitText.length * 7);
      doc.text(splitText, margin, cursorY);
      cursorY += (splitText.length * 7) + 3;
    } else if (trimmedLine.startsWith('- ') || trimmedLine.startsWith('* ')) {
      // List item
      doc.setFontSize(11);
      doc.setFont("helvetica", "normal");
      const text = '• ' + trimmedLine.substring(2);
      const splitText = doc.splitTextToSize(text, maxLineWidth - 5);
      checkPageBreak(splitText.length * 6);
      doc.text(splitText, margin + 5, cursorY);
      cursorY += (splitText.length * 6) + 2;
    } else {
      // Normal text
      doc.setFontSize(11);
      doc.setFont("helvetica", "normal");
      // Check for bolding **text** - simple check, just remove markers for now to keep it clean
      // or just print as is. Let's clean it slightly.
      const cleanLine = trimmedLine.replace(/\*\*/g, ''); 
      
      const splitText = doc.splitTextToSize(cleanLine, maxLineWidth);
      checkPageBreak(splitText.length * 6);
      doc.text(splitText, margin, cursorY);
      cursorY += (splitText.length * 6) + 2;
    }
  });
  
  doc.save(filename);
};
